name: nm_swe
channels:
  - defaults
dependencies:
  - seaborn
  - jupyter
  - pandas
  - jupyterhub
  - rioxarray
  - xarray
  - numpy
  - geopandas
  - python=3.12
  - rasterio
  - matplotlib
  - requests
  - tarfile
  - gzip
  - shutil
  - osgeo
  - calendar
  - datetime
  - os
  - contextily
  - shapely
  - pathlib
  - reportlab
